version: '3.8'

services:
  debian:
    build:
      context: ./
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - ./:/root

    network_mode: host
